### ISSUE TITLE
Cannot find name 'errorOptions'

### ISSUE THREAD

**Issue by jlchmura** [mike-lischke/antlr4ng#45]
After upgrading to v3.0.3, I'm getting a TS error in `ParseTreePatternMatcher.d.ts`:

```
[{
	"resource": "/project/node_modules/antlr4ng/dist/tree/pattern/ParseTreePatternMatcher.d.ts",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'ErrorOptions'.",
	"source": "ts",
	"startLineNumber": 87,
	"startColumn": 54,
	"endLineNumber": 87,
	"endColumn": 66
}]
```

<img width="866" alt="image" src="https://github.com/mike-lischke/antlr4ng/assets/8180397/19a6c5f1-c606-409f-b420-5eaa88d7b6c1">

**Comment by mike-lischke** [comment]
That's interesting. The error stems from TS generating the error subclass with error constructor code (which is not necessary, see `RecognitionException` which also derives from `Error` without this trouble). I guess the difference comes from the way this error is defined (as static class expression). I'll change that to isolated classes in the next release.

For now just remove this constructor manually from the d.ts file, or set "skipLibCheck" to true in your tsconfig.ts file.
